name: 'SSH Remote Commands'
description: 'Executing remote ssh commands'
author: 'Bo-Yi Wu, Paulo Henrique Cuchi'
inputs:
  host:
    description: 'ssh remote host'
  port:
    description: 'ssh remote port'
    default: 22
  passphrase:
    description: 'ssh key passphrase'
  username:
    description: 'ssh username'
  password:
    description: 'ssh password'
  key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  service_name:
    description: 'the docker swarm service name which was rolled back'
    required: true
  log_group_name:
    required: true
  log_stream_prefix:
    required: true
  
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'terminal'
  color: 'gray-dark'
